<a href="https://colab.research.google.com/github/MayuriKawale/PythonPackagesForDataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

Refer to the documentation for absolute beginners here: https://numpy.org/doc/stable/user/absolute_beginners.html
NumPy (Numerical Python) is a python package/library that provides multidimensional objects for scientific computing.

In [1]:
# Import the package
import numpy as np

# Basic Arrays

In [2]:
a = np.array([4, 6, 2, 1])
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [5]:
a[0]

np.int64(4)

In [6]:
a[3]

np.int64(1)

In [7]:
# out of range as the indexing for arrays start from 0 instead of 1
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [8]:
a[-1]

np.int64(1)

In [9]:
a[-4]

np.int64(4)

In [10]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [11]:
# Slicing the arrays
a[0:] #starting for zero till end of array

array([4, 6, 2, 1])

In [12]:
a[1:]

array([6, 2, 1])

In [13]:
a[:1] #starting from beginning and ending on given index-1

array([4])

In [14]:
a[:3]

array([4, 6, 2])

In [17]:
a[[-1]]

array([1])

In [18]:
a[[-3]]

array([6])

In [19]:
a[:-1]

array([4, 6, 2])

In [20]:
a[::2] #skipping every other index

array([4, 2])

In [21]:
a[1::2] #starting at index 1 and skipping every other index

array([6, 1])

# Array Types

In [22]:
a = np.array([2, 3, 4, 5])
b = np.array([2.0, 3.0, 4.0, 5.0])

In [23]:
type(a)

numpy.ndarray

In [24]:
a.dtype

dtype('int64')

In [25]:
type(b)

numpy.ndarray

In [26]:
b.dtype

dtype('float64')

In [29]:
c = np.array([0, 1.1, 2, 3.8])
c

array([0. , 1.1, 2. , 3.8])

In [28]:
c.dtype

dtype('float64')

In [30]:
# to ensure same data type
c = np.array([0, 1.1, 2, 3.8], dtype = float)
c

array([0. , 1.1, 2. , 3.8])

In [31]:
d = np.array([0, 1.1, 2, 3.8], dtype = int)
d

array([0, 1, 2, 3])

In [32]:
d.dtype

dtype('int64')

# Dimensions and Shapes

In [34]:
a = np.array([0,1,2,3])
a.shape

(4,)

In [36]:
A = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
A.shape

(3, 4)

In [39]:
B = np.array([
    [
      [0, 1],
      [2, 3],
      [4, 5]
    ],
    [
      [6, 7],
      [8, 9],
      [10, 11]
    ]
])
B

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [40]:
B.shape

(2, 3, 2)

In [41]:
B.ndim

3

In [42]:
B.size # no. of elements (2*3*2)

12

# Indexing and Slicing of Matrices

In [43]:
A = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
A.shape

(2, 4)

In [45]:
A[0] # first element of the array, here the first element is a list

array([0, 1, 2, 3])

In [46]:
A[1]

array([4, 5, 6, 7])

In [47]:
A[:0]

array([], shape=(0, 4), dtype=int64)

In [48]:
A[:1]

array([[0, 1, 2, 3]])

In [49]:
A[:, 0] # to include every element in the first dimension that is both the lists and giving the first index of each of those list

array([0, 4])

In [50]:
A[:, 3]

array([3, 7])

In [51]:
A[0, 0]

np.int64(0)

In [52]:
A[1, 3]

np.int64(7)

In [53]:
A[:, 1:3]

array([[1, 2],
       [5, 6]])

In [54]:
# modifying the object i.e. replacing the existing value with a new value
A[0] = np.array([8, 9, 10, 11])
A

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [55]:
# if you want to replace all the elements with the same value
A[1] = 98
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

# Statistics

In [56]:
a =  np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [57]:
a.sum()

np.int64(6)

In [58]:
a.mean()

np.float64(1.5)

In [59]:
a.std()

np.float64(1.118033988749895)

In [60]:
a.var()

np.float64(1.25)

In [61]:
a.max()

np.int64(3)

In [62]:
a.min()

np.int64(0)

In [63]:
A = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
A.sum()

np.int64(66)

In [65]:
A.mean() # for all the elements

np.float64(5.5)

In [66]:
A.std()

np.float64(3.452052529534663)

In [67]:
A.max()

np.int64(11)

In [68]:
A.min()

np.int64(0)

In [69]:
A.sum(axis=0) # sum of each columns

array([12, 15, 18, 21])

In [70]:
A.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [71]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [72]:
A.max(axis=1)

array([ 3,  7, 11])

# Linear Algebra

In [73]:
# let's use two matrices of same dimension to perform some linear algebra
A = np.array([[0, 1, 2],
              [3, 4, 5]])
B = np.array([[6, 7, 8],
              [9, 10, 11]])

In [74]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
A + B

array([[ 6,  8, 10],
       [12, 14, 16]])

In [77]:
A - B

array([[-6, -6, -6],
       [-6, -6, -6]])

In [78]:
A * B #pair-wise multiplication, not a matrix multiplication

array([[ 0,  7, 16],
       [27, 40, 55]])

In [79]:
B.T #transpose

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [81]:
# Matrix multiplication
A @ (B.T)

array([[ 23,  32],
       [ 86, 122]])

In [82]:
A.T @ B

array([[27, 30, 33],
       [42, 47, 52],
       [57, 64, 71]])

# Useful Functions

In [83]:
# a list for a given range, excluding the right most value
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(5, 10) #excluding 10

array([5, 6, 7, 8, 9])

In [85]:
np.arange(5, 10, 2) # each bin of size 2

array([5, 7, 9])

In [86]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [87]:
# reshaping an array
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [88]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.random.randint(0, 10, (10)) # random integers between 0 and 10 and shape of the array is (10, 1)

array([0, 4, 5, 4, 2, 9, 0, 7, 6, 5])

In [91]:
np.random.randint(0, 10, (5, 2))

array([[0, 4],
       [7, 2],
       [5, 7],
       [1, 5],
       [0, 1]])

In [93]:
np.random.rand(2, 4) # random float with shape (2, 4)

array([[0.56948732, 0.33464711, 0.95867032, 0.09255364],
       [0.20576154, 0.07151574, 0.58122089, 0.88873074]])

In [94]:
np.random.normal(0, 0.1, (2,3)) # normal distribution with mu=0, sigma=0.1 and shape of array (2, 3)

array([[ 0.04988066,  0.01127942,  0.02556536],
       [-0.09998678, -0.00075753, -0.16932801]])

In [97]:
a = np.random.uniform(0, 1, (2, 3))
a

array([[0.65319285, 0.03033142, 0.25399958],
       [0.11462311, 0.13215088, 0.06460616]])

In [98]:
np.sort(a) # sorts each element(here list) in the ascending order

array([[0.03033142, 0.25399958, 0.65319285],
       [0.06460616, 0.11462311, 0.13215088]])

In [99]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [100]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])